### ISSUE TITLE
ipinfo cli crashes when manually entering bulk data

### ISSUE THREAD

**Issue by MrSeccubus** [ipinfo/cli#35]
What I did.

* I typed: `ipinfo bulk`
* I typed `8.8.8.8`
* I pressed `CTRL+D`

What did I expect

The results

What happened?
```
$ ipinfo bulk
** manual input mode **
Enter all IPs, one per line:
8.8.8.8
panic: interface conversion: interface {} is *interface {}, not *ipinfo.Core

goroutine 1 [running]:
github.com/ipinfo/go/v2/ipinfo.(*Client).GetIPStrInfoBatch(0xc0000256c0, 0xc000055ce0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x3, 0xc00001a1b0, ...)
        /home/mslm/dev/ipinfo/cli/vendor/github.com/ipinfo/go/v2/ipinfo/batch.go:288 +0x285
github.com/ipinfo/go/v2/ipinfo.(*Client).GetIPInfoBatch(0xc0000256c0, 0xc000180000, 0x1, 0x2710, 0x0, 0x0, 0x0, 0x0, 0x19, 0xc00007e180, ...)
        /home/mslm/dev/ipinfo/cli/vendor/github.com/ipinfo/go/v2/ipinfo/batch.go:260 +0x17a
main.cmdBulk(0x7ffe894f0483, 0x4)
        /home/mslm/dev/ipinfo/cli/ipinfo/cmd_bulk.go:93 +0x449
main.main()
        /home/mslm/dev/ipinfo/cli/ipinfo/main.go:57 +0x398
```

**Comment by MrSeccubus** [comment]
Workaround
```
echo 8.8.8.8 > /tmp/ipinfo.txt;cat /tmpo/ipinfo.txt | ipinfo
```

**Comment by MrSeccubus** [comment]
Another one that doesn't work:
```
$ echo 8.8.8.8 | ipinfo bulk
panic: interface conversion: interface {} is *interface {}, not *ipinfo.Core

goroutine 1 [running]:
github.com/ipinfo/go/v2/ipinfo.(*Client).GetIPStrInfoBatch(0xc0000256c0, 0xc000055ce0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x3, 0xc00001a180, ...)
        /home/mslm/dev/ipinfo/cli/vendor/github.com/ipinfo/go/v2/ipinfo/batch.go:288 +0x285
github.com/ipinfo/go/v2/ipinfo.(*Client).GetIPInfoBatch(0xc0000256c0, 0xc000180000, 0x1, 0x2710, 0x0, 0x0, 0x0, 0x0, 0x19, 0xc00007e180, ...)
        /home/mslm/dev/ipinfo/cli/vendor/github.com/ipinfo/go/v2/ipinfo/batch.go:260 +0x17a
main.cmdBulk(0x7ffe46d51483, 0x4)
        /home/mslm/dev/ipinfo/cli/ipinfo/cmd_bulk.go:93 +0x449
main.main()
        /home/mslm/dev/ipinfo/cli/ipinfo/main.go:57 +0x398
```

**Comment by UmanShahzad** [comment]
Solved in https://github.com/ipinfo/cli/releases/tag/ipinfo-1.1.2
