### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by mbierman** [ipinfo/cli#43]
```
==> Upgrading 1 outdated package:
ipinfo-cli 1.1.3 -> 1.1.5
==> Upgrading ipinfo-cli 1.1.3 -> 1.1.5 
==> Downloading https://ghcr.io/v2/homebrew/core/ipinfo-cli/manifests/1.1.5
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/ipinfo-cli/blobs/sha256:215f6613824d7d14ff932d2aa835be7858fe62c046dfe2e22d3bf170f75c0f1c
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:215f6613824d7d14ff932d2aa835be7858fe62c046dfe2e22d3bf170f75c0f1c?se=2021-
######################################################################## 100.0%
==> Pouring ipinfo-cli--1.1.5.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/ipinfo-cli/1.1.5: 5 files, 7.3MB
Removing: /usr/local/Cellar/ipinfo-cli/1.1.3... (5 files, 7.3MB)
Removing: /Users/bierman/Library/Caches/Homebrew/ipinfo-cli--1.1.3... (3.8MB)
cleaning up brew...
Error: 767: unexpected token at '{
  "ipinfo-cli": "homebrew/core"
  "grepip": "homebrew/core"
}
'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tap.rb:605:in `tap_migrations'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:322:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:302:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:508:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:508:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:404:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:452:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:425:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:85:in `stale_formula?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:58:in `stale?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:321:in `block in cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:304:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:304:in `cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:192:in `clean!'
/usr/local/Homebrew/Library/Homebrew/cmd/cleanup.rb:58:in `cleanup'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

**Comment by UmanShahzad** [comment]
Sorry about that, missing comma! Should be fixed now.
