### ISSUE TITLE
[bug]: runtime error: index out of range [3] with length 0

### ISSUE THREAD

**Issue by T145** [ipinfo/cli#62]
```
panic: runtime error: index out of range [3] with length 0

goroutine 1 [running]:
encoding/binary.bigEndian.Uint32(...)
	/usr/lib/go-1.16/src/encoding/binary/binary.go:112
github.com/ipinfo/cli/lib.IPFromStdIP(0x0, 0x0, 0x0, 0x1)
	/go/pkg/mod/github.com/ipinfo/cli@v0.0.0-20210913060407-f42b3e3bb94c/lib/ip.go:24 +0x86
github.com/ipinfo/cli/lib.CmdGrepIP.func1(0x5c713d, 0x10, 0x5fc468, 0xc0000b6000)
	/go/pkg/mod/github.com/ipinfo/cli@v0.0.0-20210913060407-f42b3e3bb94c/lib/cmd_grepip.go:261 +0xbf5
github.com/ipinfo/cli/lib.CmdGrepIP(0x100010000000101, 0xc000092740, 0x0, 0x1, 0x5d1340, 0x0, 0x5d0309)
	/go/pkg/mod/github.com/ipinfo/cli@v0.0.0-20210913060407-f42b3e3bb94c/lib/cmd_grepip.go:324 +0x57b
main.cmd(0x7ffd24fadb1d, 0x6)
	/go/pkg/mod/github.com/ipinfo/cli@v0.0.0-20210913060407-f42b3e3bb94c/grepip/main.go:128 +0x3f3
main.main()
	/go/pkg/mod/github.com/ipinfo/cli@v0.0.0-20210913060407-f42b3e3bb94c/grepip/main.go:139 +0x85
Error: Process completed with exit code 2.
```

**Comment by UmanShahzad** [comment]
@T145 thanks for the report. Can you show the command you ran to hit this case?

**Comment by T145** [comment]
I'm not sure exactly. It was generated while running [Black Mirror](https://github.com/T145/black-mirror), and could've been from any list contents. List output got piped into `grepip -4xo` or `grepip -6xo` for respective IPv4 and IPv6 content to filter bogons and such as testing.

**Comment by UmanShahzad** [comment]
Alright it seems it'd only happen if the regex we use internally did not actually select a proper IP (I can see that our v4 regex is too loose and accepts e.g. `999.999.999.999`), but we assume it is and pass it over to an IP string parser which then returns nil, and that nil goes down and causes issues because it's unexpected.

Will fix this in the next release which should be this week.
