### ISSUE TITLE
[Bug]: Certain IPv6 addresses are not being recognized

### ISSUE THREAD

**Issue by T145** [ipinfo/cli#71]
Examples include:
```
2001:2030:21:18f::27dc
2001:2030:21:1a0::27dc
2001:2030:21:1a1::27dc
2001:2030:21:1a6::27dc
2001:2030:21:1b5::27dc
2001:2030:22::3e73:fdca
2001:2030:22::3e73:fde8
2001:4998:64:800::6000
2001:4998:64:800::6001
2400:3200:1500::f9
2401:8700:ff04::28
2401:b180:2000:30::2e
2401:b180:2000:50::e
2401:b180:2000:60::13
2401:b180:2000:80::10
2401:b180:7003::1fb
2401:b180:7003::8c
2402:4e00:40:40::2:30f
2402:4e00:8020:2::53
2402:4e00:8030:1::83
2402:4e00:8030:1::84
2408:4001:f00::117
2408:4001:f00::135
2408:4001:f00::19
2408:4001:f00::1af
2408:4001:f00::1b7
2408:4001:f00::1c9
2408:4001:f00::1fa
2408:4001:f00::20d
2408:4001:f00::21
2408:4001:f00::251
2408:4001:f00::289
2408:4001:f00::29f
2408:4001:f00::2ea
2408:4001:f00::2f
2408:4001:f00::b4
2408:4001:f10::fd
2408:4002:1f10::109
2408:4004:1f8::1a1
2408:80f1:100:1010::29
2408:80f1:100:1010::d
2408:80f1:21:4013::84
2408:80f1:21:4013::88
2408:80f1:31:10::4f
2408:8711:10:10::55
2408:8752:0:2:30::1
2408:8752:0:2:30::2
2408:8752:0:2:30::3
2408:8752:0:2:30::4
2408:8752:0:30:30::1
2408:8752:0:30:30::2
2408:8752:0:e:30::1
2408:8752:0:e:30::2
2408:8752:0:e:30::4
2408:8756:3af0:10::16a
240d:c040:0:40::116
240d:c040:1:40::11d
240e:83:201:110::7
240e:83:201:4d10::3df9
240e:b1:a810:1800::6a75:d82a
240e:ff:f101:10::1a0
240e:ff:f101:10::1a3
2600:1409:7800::17dd:df12
2600:1409:7800::17dd:df39
2600:1409:9800:784::27dc
2600:1409:9800:786::27dc
2600:1409:9800:788::27dc
2600:1409:9800:78a::27dc
2600:1409:9800:78c::27dc
2600:3c02::f03c:91ff:fee2:5b0f
2604:980:7002:6::2c
2604:980:7002:6::2d
2606:4700:3033::6815:4699
2606:4700:3033::ac43:a864
2606:ae80:1451:22::820
2607:a400:2:b::4
2607:f8b0:400a:801::2008
2607:f8b0:400a:801::200e
2607:f8b0:400a:80a::2001
2607:f8b0:400a:80b::2002
2607:f8b0:400a:80b::2006
2620:1ec:46::70
2620:1ec:bdf::70
2a00:1288:80:800::7000
2a00:1288:80:800::7001
2a00:1450:4010:c08::64
2a00:1450:4010:c08::65
2a00:1450:4010:c08::8a
2a00:1450:4010:c08::8b
2a00:1450:4010:c0b::9a
2a00:1450:4010:c0b::9b
2a00:1450:4010:c0b::9c
2a00:1450:4010:c0b::9d
2a01:53c0:ff0f::2e
2a01:53c0:ff0f::34
2a0d:5300:10::2
2a0d:5300:10::3
```

**Comment by T145** [comment]
Error log:
```
panic: runtime error: index out of range [3] with length 0

goroutine 1 [running]:
encoding/binary.bigEndian.Uint32(...)
	/usr/lib/go-1.17/src/encoding/binary/binary.go:112
github.com/ipinfo/cli/lib.IPFromStdIP({0x0, 0xc00001e160, 0x82784c})
	/go/pkg/mod/github.com/ipinfo/cli@v0.0.0-20211109184218-db5c4c003397/lib/ip.go:24 +0x45
github.com/ipinfo/cli/lib.CmdGrepIP.func1({0x7ffffd27babe, 0x13}, {0x82d580, 0xc000010550})
	/go/pkg/mod/github.com/ipinfo/cli@v0.0.0-20211109184218-db5c4c003397/lib/cmd_grepip.go:265 +0x766
github.com/ipinfo/cli/lib.CmdGrepIP.func2({0x7ffffd27babe, 0x13})
	/go/pkg/mod/github.com/ipinfo/cli@v0.0.0-20211109184218-db5c4c003397/lib/cmd_grepip.go:326 +0x5f
github.com/ipinfo/cli/lib.CmdGrepIP({0x1, 0x1, 0x0, 0x0, 0x0, 0x1, 0x0, 0x1}, {0xc0000719f0, 0x1, ...}, ...)
	/go/pkg/mod/github.com/ipinfo/cli@v0.0.0-20211109184218-db5c4c003397/lib/cmd_grepip.go:343 +0x8a2
main.cmdGrepIP()
	/go/pkg/mod/github.com/ipinfo/cli@v0.0.0-20211109184218-db5c4c003397/ipinfo/cmd_grepip.go:65 +0x105
main.main()
	/go/pkg/mod/github.com/ipinfo/cli@v0.0.0-20211109184218-db5c4c003397/ipinfo/main.go:55 +0x1ef
```

**Comment by UmanShahzad** [comment]
The currrent ipv6 regex seems to have issues properly parsing compressed IPv6 forms where the compression happens in the middle (but works fine if in the start or end). But after some testing it turns out the issue is not with the regex itself but that we were not using the POSIX version of the regex parser. Using that fixes things.

However the error log you shared doesn't happen for me when run against the input IPs shown above even without the fix. It seems to happen for IPv4 cases only, and also seems to be a replica of https://github.com/ipinfo/cli/issues/62 but not sure how that's possible as the regex is pretty solid now.

If you could help me find an exact input that caused that error, it should be an easy fix.

**Comment by UmanShahzad** [comment]
The fix for the ipv6 case is live now on `grepip` version 1.2.1 and `ipinfo` 2.4.1.
